server:
  port: 50001

spring:
  jwt:
    secret: "msa-project"
  application:
    name: user-service-msa
  datasource:
    url: jdbc:mysql://172.72.0.1:1003/msa?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        # DB physical-name upper-case
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

group:
  name: "USER_NAME"
