server:
  port: 4001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
spring:
  profiles:
    active: local

# config Server (Dynamic Setting)
#spring:
#  application:
#    name: api-gateway
#  rabbitmq:
#    host: 127.0.0.1
#    port: 1001
#    username: admin
#    password: admin
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#            - Method=GET
#          filters:
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order-service/**
#            - Method=GET
#          filters:
#            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
#      discovery:
#        locator:
#          lower-case-service-id: true
#          enabled: true